<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>7</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>92d4de27-cfbf-4ff7-99d8-f5aaadf2b465</testSuiteGuid>
   <testCaseLink>
      <guid>fed11f28-d87f-40ab-aa01-6f14ced4e351</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day2/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d0e07bb3-46f4-419e-ab95-907a0780d92c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DataOne</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d0e07bb3-46f4-419e-ab95-907a0780d92c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>a4fc77e5-de03-464b-a8cc-dd5b27462dee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d0e07bb3-46f4-419e-ab95-907a0780d92c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>5c4d6669-a723-4a44-9d94-770a15b00237</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
